/*
    This file was automatically generated by Studio 3T.

    Collection: atlas-bom5la-shard-0 (foo@cluster0.akft6.mongodb.net) > test > prontuarios

    Warnings about type conversion issues are stored as comments above the
    corresponding INSERT statement of each document.
*/


SET NAMES 'utf8';

DROP TABLE IF EXISTS "prontuarios";
CREATE TABLE "prontuarios" (
    "created" TIMESTAMP,
    "content.Dados Pessoais" TEXT,
    "content.Especialidade" TEXT,
    "content.Usuário" TEXT,
    "content.Raça" TEXT,
    "content.Sexo" TEXT,
    "content.CNS" TEXT,
    "content.Data de Nascimento" TEXT,
    "content.Idade" TEXT,
    "content.20234567890" TEXT,
    "content.Fone" TEXT,
    "content.Pai" TEXT,
    "content.Mãe" TEXT,
    "content.Profissão" TEXT,
    "content.Endereço" TEXT,
    "content.Complemento" TEXT,
    "content.Cidade" TEXT,
    "content.CEP" TEXT,
    "content.Bairro" TEXT,
    "content.Hora de atendimento" TEXT,
    "content.Hora de triagem" TEXT,
    "content.Hora de consulta" TEXT,
    "content.Queixa principal" TEXT,
    "content.Observação" TEXT,
    "content.Glicemia" TEXT,
    "content.Batimentos" TEXT,
    "content.Peso" TEXT,
    "content.Pressão" TEXT,
    "content.Altura" TEXT,
    "content.Temperatura" TEXT,
    "content.Classificação" TEXT,
    "content.Alergias" TEXT,
    "content.Reavaliação" TEXT,
    "content.Medida" TEXT,
    "content.HMA" TEXT,
    "content.Medicação" TEXT,
    "content.rg" TEXT
);

INSERT INTO "prontuarios" ("created", "content.Dados Pessoais", "content.Especialidade", "content.Usuário", "content.Raça", "content.Sexo", "content.CNS", "content.Data de Nascimento", "content.Idade", "content.20234567890", "content.Fone", "content.Pai", "content.Mãe", "content.Profissão", "content.Endereço", "content.Complemento", "content.Cidade", "content.CEP", "content.Bairro", "content.Hora de atendimento", "content.Hora de triagem", "content.Hora de consulta", "content.Queixa principal", "content.Observação", "content.Glicemia", "content.Batimentos", "content.Peso", "content.Pressão", "content.Altura", "content.Temperatura", "content.Classificação", "content.Alergias", "content.Reavaliação", "content.Medida", "content.HMA", "content.Medicação", "content.rg")
    VALUES
        ('2020-10-25T23:30:46.793', 'Paulo Henrique', 'Oecologista', 'sana Vasconcelos', 'Branca', 'F', '123', '29106192', '2x', 'RG', '34 88888888', 'to Vasconcelos', 'Maria de Almeida', 'Vendedor', 'Rio dos feares', 'Casa', 'Upescindia', '3840 DOUF: MG', 'São Jo', '17:35', '17:45', '18:30', 'Dor de cabeça', 'objeti', '', '', '82', '', '175', '_ 375', 'de Risco   Vermelho  Laranja   Amarelo   Verde X Azul', 'Lennuma', '', 'inicial', '', '', 'e');
INSERT INTO "prontuarios" ("created", "content.Dados Pessoais", "content.Especialidade", "content.Usuário", "content.Raça", "content.Sexo", "content.CNS", "content.Data de Nascimento", "content.Idade", "content.20234567890", "content.Fone", "content.Pai", "content.Mãe", "content.Profissão", "content.Endereço", "content.Complemento", "content.Cidade", "content.CEP", "content.Bairro", "content.Hora de atendimento", "content.Hora de triagem", "content.Hora de consulta", "content.Queixa principal", "content.Observação", "content.Glicemia", "content.Batimentos", "content.Peso", "content.Pressão", "content.Altura", "content.Temperatura", "content.Classificação", "content.Alergias", "content.Reavaliação", "content.Medida", "content.HMA", "content.Medicação", "content.rg")
    VALUES
        ('2020-10-25T23:34:26.362', 'Paulo Henrique', 'Oecologista', 'sana Vasconcelos', 'Branca', 'F', '123', '29106192', '2x', 'RG', '34 88888888', 'to Vasconcelos', 'Maria de Almeida', 'Vendedor', 'Rio dos feares', 'Casa', 'Upescindia', '3840 DOUF: MG', 'São Jo', '17:35', '17:45', '18:30', 'Dor de cabeça', 'objeti', '', '', '82', '', '175', '_ 375', 'de Risco   Vermelho  Laranja   Amarelo   Verde X Azul', 'Lennuma', '', 'inicial', '', '', 'e');
INSERT INTO "prontuarios" ("created", "content.Dados Pessoais", "content.Especialidade", "content.Usuário", "content.Raça", "content.Sexo", "content.CNS", "content.Data de Nascimento", "content.Idade", "content.20234567890", "content.Fone", "content.Pai", "content.Mãe", "content.Profissão", "content.Endereço", "content.Complemento", "content.Cidade", "content.CEP", "content.Bairro", "content.Hora de atendimento", "content.Hora de triagem", "content.Hora de consulta", "content.Queixa principal", "content.Observação", "content.Glicemia", "content.Batimentos", "content.Peso", "content.Pressão", "content.Altura", "content.Temperatura", "content.Classificação", "content.Alergias", "content.Reavaliação", "content.Medida", "content.HMA", "content.Medicação", "content.rg")
    VALUES
        ('2020-10-25T23:34:59.699', 'Paulo Henrique', 'Oecologista', 'sana Vasconcelos', 'Branca', 'F', '123', '29106192', '2x', 'RG', '34 88888888', 'to Vasconcelos', 'Maria de Almeida', 'Vendedor', 'Rio dos feares', 'Casa', 'Upescindia', '3840 DOUF: MG', 'São Jo', '17:35', '17:45', '18:30', 'Dor de cabeça', 'objeti', '', '', '82', '', '175', '_ 375', 'de Risco   Vermelho  Laranja   Amarelo   Verde X Azul', 'Lennuma', '', 'inicial', '', '', 'e');
INSERT INTO "prontuarios" ("created", "content.Dados Pessoais", "content.Especialidade", "content.Usuário", "content.Raça", "content.Sexo", "content.CNS", "content.Data de Nascimento", "content.Idade", "content.20234567890", "content.Fone", "content.Pai", "content.Mãe", "content.Profissão", "content.Endereço", "content.Complemento", "content.Cidade", "content.CEP", "content.Bairro", "content.Hora de atendimento", "content.Hora de triagem", "content.Hora de consulta", "content.Queixa principal", "content.Observação", "content.Glicemia", "content.Batimentos", "content.Peso", "content.Pressão", "content.Altura", "content.Temperatura", "content.Classificação", "content.Alergias", "content.Reavaliação", "content.Medida", "content.HMA", "content.Medicação", "content.rg")
    VALUES
        ('2020-10-25T23:35:42.720', 'Paulo Henrique', 'Oecologista', 'sana Vasconcelos', 'Branca', 'F', '123', '29106192', '2x', 'RG', '34 88888888', 'to Vasconcelos', 'Maria de Almeida', 'Vendedor', 'Rio dos feares', 'Casa', 'Upescindia', '3840 DOUF: MG', 'São Jo', '17:35', '17:45', '18:30', 'Dor de cabeça', 'objeti', '', '', '82', '', '175', '_ 375', 'de Risco   Vermelho  Laranja   Amarelo   Verde X Azul', 'Lennuma', '', 'inicial', '', '', 'e');
INSERT INTO "prontuarios" ("created", "content.Dados Pessoais", "content.Especialidade", "content.Usuário", "content.Raça", "content.Sexo", "content.CNS", "content.Data de Nascimento", "content.Idade", "content.20234567890", "content.Fone", "content.Pai", "content.Mãe", "content.Profissão", "content.Endereço", "content.Complemento", "content.Cidade", "content.CEP", "content.Bairro", "content.Hora de atendimento", "content.Hora de triagem", "content.Hora de consulta", "content.Queixa principal", "content.Observação", "content.Glicemia", "content.Batimentos", "content.Peso", "content.Pressão", "content.Altura", "content.Temperatura", "content.Classificação", "content.Alergias", "content.Reavaliação", "content.Medida", "content.HMA", "content.Medicação", "content.rg")
    VALUES
        ('2020-10-25T23:36:04.653', 'Paulo Henrique', 'Oecologista', 'sana Vasconcelos', 'Branca', 'F', '123', '29106192', '2x', 'RG', '34 88888888', 'to Vasconcelos', 'Maria de Almeida', 'Vendedor', 'Rio dos feares', 'Casa', 'Upescindia', '3840 DOUF: MG', 'São Jo', '17:35', '17:45', '18:30', 'Dor de cabeça', 'objeti', '', '', '82', '', '175', '_ 375', 'de Risco   Vermelho  Laranja   Amarelo   Verde X Azul', 'Lennuma', '', 'inicial', '', '', 'e');
INSERT INTO "prontuarios" ("created", "content.Dados Pessoais", "content.Especialidade", "content.Usuário", "content.Raça", "content.Sexo", "content.CNS", "content.Data de Nascimento", "content.Idade", "content.20234567890", "content.Fone", "content.Pai", "content.Mãe", "content.Profissão", "content.Endereço", "content.Complemento", "content.Cidade", "content.CEP", "content.Bairro", "content.Hora de atendimento", "content.Hora de triagem", "content.Hora de consulta", "content.Queixa principal", "content.Observação", "content.Glicemia", "content.Batimentos", "content.Peso", "content.Pressão", "content.Altura", "content.Temperatura", "content.Classificação", "content.Alergias", "content.Reavaliação", "content.Medida", "content.HMA", "content.Medicação", "content.rg")
    VALUES
        ('2020-10-25T23:41:36.359', 'Paulo Henrique', 'Oecologista', 'sana Vasconcelos', 'Branca', 'F', '123', '29106192', '2x', 'RG', '34 88888888', 'to Vasconcelos', 'Maria de Almeida', 'Vendedor', 'Rio dos feares', 'Casa', 'Upescindia', '3840 DOUF: MG', 'São Jorge', '17:35', '17:45', '18:30', 'Dor de cabeça', 'objeti', '', '', '82', '', '175', '_ 375', 'de Risco   Vermelho  Laranja   Amarelo   Verde X Azul', 'Lennuma', '', 'inicial', '', '', NULL);
INSERT INTO "prontuarios" ("created", "content.Dados Pessoais", "content.Especialidade", "content.Usuário", "content.Raça", "content.Sexo", "content.CNS", "content.Data de Nascimento", "content.Idade", "content.20234567890", "content.Fone", "content.Pai", "content.Mãe", "content.Profissão", "content.Endereço", "content.Complemento", "content.Cidade", "content.CEP", "content.Bairro", "content.Hora de atendimento", "content.Hora de triagem", "content.Hora de consulta", "content.Queixa principal", "content.Observação", "content.Glicemia", "content.Batimentos", "content.Peso", "content.Pressão", "content.Altura", "content.Temperatura", "content.Classificação", "content.Alergias", "content.Reavaliação", "content.Medida", "content.HMA", "content.Medicação", "content.rg")
    VALUES
        ('2020-10-25T23:47:59.184', 'Paulo Henrique', 'Oecologista', 'sana Vasconcelos', 'Branca', 'F', '123', '29106192', '2x', 'RG', '34 88888888', 'to Vasconcelos', 'Maria de Almeida', 'Vendedor', 'Rio dos feares', 'Casa', 'Upescindia', '3840 DOUF: MG', 'São Jorge', '17:35', '17:45', '18:30', 'Dor de cabeça', 'objeti', '', '', '82', '', '175', '_ 375', 'de Risco   Vermelho  Laranja   Amarelo   Verde X Azul', 'Lennuma', '', 'inicial', '', '', NULL);
INSERT INTO "prontuarios" ("created", "content.Dados Pessoais", "content.Especialidade", "content.Usuário", "content.Raça", "content.Sexo", "content.CNS", "content.Data de Nascimento", "content.Idade", "content.20234567890", "content.Fone", "content.Pai", "content.Mãe", "content.Profissão", "content.Endereço", "content.Complemento", "content.Cidade", "content.CEP", "content.Bairro", "content.Hora de atendimento", "content.Hora de triagem", "content.Hora de consulta", "content.Queixa principal", "content.Observação", "content.Glicemia", "content.Batimentos", "content.Peso", "content.Pressão", "content.Altura", "content.Temperatura", "content.Classificação", "content.Alergias", "content.Reavaliação", "content.Medida", "content.HMA", "content.Medicação", "content.rg")
    VALUES
        ('2020-10-26T00:42:52.324', 'Paulo Henrique', 'Oecologista', 'sana Vasconcelos', 'Branca', 'F', '123', '29106192', '2x', 'RG', '34 88888888', 'to Vasconcelos', 'Maria de Almeida', 'Vendedor', 'Rio dos feares', 'Casa', 'Upescindia', '3840 DOUF: MG', 'São Jorge', '17:35', '17:45', '18:30', 'Dor de cabeça', 'objeti', '', '', '82', '', '175', '_ 375', 'de Risco   Vermelho  Laranja   Amarelo   Verde X Azul', 'Lennuma', '', 'inicial', '', '', NULL);
INSERT INTO "prontuarios" ("created", "content.Dados Pessoais", "content.Especialidade", "content.Usuário", "content.Raça", "content.Sexo", "content.CNS", "content.Data de Nascimento", "content.Idade", "content.20234567890", "content.Fone", "content.Pai", "content.Mãe", "content.Profissão", "content.Endereço", "content.Complemento", "content.Cidade", "content.CEP", "content.Bairro", "content.Hora de atendimento", "content.Hora de triagem", "content.Hora de consulta", "content.Queixa principal", "content.Observação", "content.Glicemia", "content.Batimentos", "content.Peso", "content.Pressão", "content.Altura", "content.Temperatura", "content.Classificação", "content.Alergias", "content.Reavaliação", "content.Medida", "content.HMA", "content.Medicação", "content.rg")
    VALUES
        ('2020-10-26T00:47:17.042', 'Paulo Henrique', 'Oecologista', 'sana Vasconcelos', 'Branca', 'F', '123', '29106192', '2x', 'RG', '34 88888888', 'to Vasconcelos', 'Maria de Almeida', 'Vendedor', 'Rio dos feares', 'Casa', 'Upescindia', '3840 DOUF: MG', 'São Jorge', '17:35', '17:45', '18:30', 'Dor de cabeça', 'objeti', '', '', '82', '', '175', '_ 375', 'de Risco   Vermelho  Laranja   Amarelo   Verde X Azul', 'Lennuma', '', 'inicial', '', '', NULL);
